
# JEU DES DEVINETTES

# 1. PRENDRE UN NOMBRE ALÉATOIRE ENTRE 1 ET 100
# 2. FAIRE DEVINER UN NOMBRE AU JOUEUR
# 3. COMPARER AVEC LE NOMBRE ALÉATOIRE
# 4. DONNER LE RÉSULTAT DE LA COMPARAISON AU JOUEUR
# 5. LE JOUEUR A 10 ESSAIS POUR DEVINER -> REVENIR À L'ÉTAPE 2
# 6. AFFICHER LA SOLUTION SI LE JOUEUR A PERDU
# 7. AFFICHER LE NOMBRE D'ESSAIS SI LE JOUEUR A GAGNÉ


import random

nombre_aleatoire = random.randint(1, 100)

# boucle for...?